# 1. Identity
spring.application.name=configserver
server.port=8888

# 2. Activate Local File Mode
spring.profiles.active=native

# 3. Path to your files
# 'classpath' points to src/main/resources
spring.cloud.config.server.native.search-locations=classpath:/config

# 4. (Optional but Recommended) 
# Disable Eureka for the Config Server so it doesn't complain in the logs
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false