spring.application.name=eureka-server
server.port=8761


eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
spring.config.import=optional:configserver: instead
# Force it to register with its IP instead of the buggy hostname
eureka.instance.prefer-ip-address=true
# Or, for absolute safety on a single machine:
eureka.instance.hostname=localhost

# 4. Optional: Clean up logs
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
