spring.application.name=ai-service
server.port=8083
# This replaces host, port, and database in one go
spring.data.mongodb.uri=mongodb://localhost:27017/fitness_recommendations
eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.requested-heartbeat=30
# The virtual host you defined in your Docker command
# spring.rabbitmq.virtual-host=my_vhost

# messaging.queue.activity=fitness.activityservice.rabbitmq

# Default credentials
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest



spring.ai.google.genai.chat.options.model=gemini-2.5-flash

# Enable retries
spring.rabbitmq.listener.simple.retry.enabled=true
# How many times to try before giving up
spring.rabbitmq.listener.simple.retry.max-attempts=3
# How long to wait between tries (2 seconds)
spring.rabbitmq.listener.simple.retry.initial-interval=2000ms
# The maximum wait time between tries
spring.rabbitmq.listener.simple.retry.max-interval=10000ms