

# Connect to the Eureka Registry
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

eureka.instance.hostname=localhost
# THE GATEWAY PORT
server.port=8080


eureka.instance.prefer-ip-address=true

# routing Rules
spring.cloud.gateway.server.webflux.routes[0].id=activity-route
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ACTIVITY-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/activities/**

spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/users/**

spring.cloud.gateway.server.webflux.routes[2].id=ai-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://AI-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/ai/**



# Optional: Helpful for debugging if the route isn't picked up
spring.cloud.gateway.server.webflux.discovery.locator.enabled=false

#Expose the gateway actuator endpoints
management.endpoints.web.exposure.include=gateway,health,info
# Enable the gateway-specific features in actuator
management.endpoint.gateway.access=unrestricted


# 1. Disable the auto-locator so it doesn't "hijack" your manual routes

# 1. Tell Spring where to find the public keys
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8090/realms/fitness-oauth2/protocol/openid-connect/certs

# 2. Tell Spring what the "Official" name of the issuer is (for validation)
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/my-spring-realm

# 3. (Optional) Helpful for debugging security issues
#logging.level.org.springframework.security=DEBUG